#!/bin/sh
# Establece "123456" como clave de usuario y "123456" para root
# el hash se genero mediante: openssl passwd clave 
usermod -p 'gBBmIRKwFKpOY' root
usermod -p 'gBBmIRKwFKpOY' user
chown -R user:user /home/user/
chmod -R g=-r-x,o=-r-x /home/user/
